<?php
return array(
    'OnDocFormPrerender'=>[
        'autentiments'
    ],
    'OnLoadWebDocument'=>[
        'registerFrontVariables',
    ],
    'msOnBeforeCreateOrder'=>[
        'roistat'
    ],
    'mSyncOnPrepareProduct'=>[
        'mSyncModifications'
    ],
    'mSyncOnProductImport'=>[
        'mSyncModifications'
    ],
    'mSyncOnProductOffers'=>[
        'mSyncModifications'
    ],
    'mSyncOnSalesExport'=>[
        'mSyncModifications'
    ]
);